spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  batch:
    job:
      enabled: false
  datasource:
    hikari:
      batch:
        password:
        username: sa
        jdbcUrl: jdbc:h2:tcp://localhost/~/workspace/h2/data/batch
        driverClassName: org.h2.Driver
      catalog:
        password:
        username: sa
        jdbcUrl: jdbc:h2:tcp://localhost/~/workspace/h2/data/catalog
        driverClassName: org.h2.Driver
      secondary:
        password:
        username: sa
        jdbcUrl: jdbc:h2:tcp://localhost/~/workspace/h2/data/local
        driverClassName: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
striim:
  source.directory: /tmp
  target.directory: /tmp